### ISSUE TITLE
Some links lead to 404s..

### ISSUE THREAD

**Issue by amchagas** [MakerTobey/OpenMicrofluidics#4]
Hi!

This is super interesting!
Some links are leading to 404/403 errors though:

https://github.com/MakerTobey/OpenMicrofluidics/tree/master/Open%20FADS

https://github.com/MakerTobey/OpenMicrofluidics/tree/master/pressure%20control%20bild%20and%20test

https://media.proquest.com/media/pq/classic/doc/4322030507/fmt/ai/rep/NPDF?_s=EUAbzVz%2B%2FEKGyiix9oguFSmtgAU%3D

**Comment by MakerTobey** [comment]
Thanks a lot! now fixed.
